[package]
name = "Chess-Game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe="0.25.0"
image={version="0.24.7", features=["png", "jpeg"]}
egui_extras={version="0.25.0", features=["all_loaders"]}
duration-string={version = "0.3.0"}

[dev-dependencies]
criterion="0.5.1"

[[bench]]
name="chess-benchmark"
harness=false